// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOy1aP8lXoadbsHutp2JU4IAqa0Fr6Rrg',
    appId: '1:778820470736:web:0ea16fc07e83a3c4ce9bd5',
    messagingSenderId: '778820470736',
    projectId: 'visaoletrada',
    authDomain: 'visaoletrada.firebaseapp.com',
    storageBucket: 'visaoletrada.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXEh_BsvgmQ0Cooj7DtZ35Tj5UdKOEfIY',
    appId: '1:778820470736:android:ac68518b62c06abece9bd5',
    messagingSenderId: '778820470736',
    projectId: 'visaoletrada',
    storageBucket: 'visaoletrada.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHWjWkUNZe_F6ESVPxGLiGNtfyowZSGiw',
    appId: '1:778820470736:ios:7b70bd5491779b76ce9bd5',
    messagingSenderId: '778820470736',
    projectId: 'visaoletrada',
    storageBucket: 'visaoletrada.firebasestorage.app',
    iosBundleId: 'com.example.visaoletrada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHWjWkUNZe_F6ESVPxGLiGNtfyowZSGiw',
    appId: '1:778820470736:ios:7b70bd5491779b76ce9bd5',
    messagingSenderId: '778820470736',
    projectId: 'visaoletrada',
    storageBucket: 'visaoletrada.firebasestorage.app',
    iosBundleId: 'com.example.visaoletrada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOy1aP8lXoadbsHutp2JU4IAqa0Fr6Rrg',
    appId: '1:778820470736:web:012c2dd71bce5e34ce9bd5',
    messagingSenderId: '778820470736',
    projectId: 'visaoletrada',
    authDomain: 'visaoletrada.firebaseapp.com',
    storageBucket: 'visaoletrada.firebasestorage.app',
  );
}
